---
ID: "83567d2f-c7c3-4e8d-be33-208515d79605"
Parent: "483eefa1-df25-4442-bdc2-7838a53eaac7"
Template: "1226c3c7-2d1f-48f5-87b4-c1da459f05e5"
Path: /sitecore/content/Verticals/BettyCrocker/Home/products
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{E9B6C600-C6E8-4867-BCB7-8B0DC5F19840}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 150
- ID: "df6dc0ca-f8ee-493a-a920-f2b710f08452"
  Hint: BackgroundImage
  Value: |
    <image mediaid="{01D31F24-D9AC-4AA3-95CE-F81D45E17BE2}" alt="house-key-calculator-with-dollar-bills" height="" width="" hspace="" vspace="" />
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{FA3AF3E9-7260-4835-9970-36524246AD28}"
          p:before="*"
          s:ds="local:/Data/Three Column CTA 1"
          s:id="{AD385021-CE2B-4FC1-89AA-207D408034A8}"
          s:par="FieldNames&amp;RenderingIdentifier&amp;Styles=%7C%7BB34B13D3-C354-4204-9341-B726038AB516%7D&amp;CSSStyles&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;DynamicPlaceholderId=5"
          s:ph="/headless-main/sxa-page-content/background-page-content-0-1" />
        <r
          uid="{E25AB7CC-356F-4A00-A1EB-CEEFBE5578BB}"
          p:after="r[@uid='{FA3AF3E9-7260-4835-9970-36524246AD28}']"
          s:ds="local:/Data/Promo CTA 1"
          s:id="{1A375FAC-6CC1-4A5A-A159-9BC6DBC66B80}"
          s:par="FieldNames&amp;RenderingIdentifier&amp;Styles=%7C%7BE35B0857-0823-4A02-AEF5-3BD2A47770FF%7D&amp;CSSStyles&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;DynamicPlaceholderId=6"
          s:ph="/headless-main/sxa-page-content/background-page-content-0-1" />
        <r
          uid="{2F983DB6-9A36-4A3E-90B6-86E5BF533E37}"
          p:after="r[@uid='{E25AB7CC-356F-4A00-A1EB-CEEFBE5578BB}']"
          s:ds="local:/Data/Promo CTA 2"
          s:id="{1A375FAC-6CC1-4A5A-A159-9BC6DBC66B80}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles=%7C%7BC9549A3A-3226-4FA8-B81E-C2875D29D821%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=8"
          s:ph="/headless-main/sxa-page-content/background-page-content-0-1" />
        <r
          uid="{63DF3333-CECD-4865-B2BA-A97063A9718E}"
          p:after="r[@uid='{2F983DB6-9A36-4A3E-90B6-86E5BF533E37}']"
          s:ds="local:/Data/Questions 1"
          s:id="{75464A5E-CBB7-4F96-BBBC-104AFE57923A}"
          s:par="FieldNames&amp;RenderingIdentifier&amp;Styles=%7C%7B54351712-760E-4F9D-8FC5-DAA43B0D8335%7D&amp;CSSStyles&amp;GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;DynamicPlaceholderId=7"
          s:ph="/headless-main/sxa-page-content/background-page-content-0-1" />
        <r
          uid="{668594D0-1879-467B-89BF-B7AF1689CDC8}"
          p:after="r[@uid='{63DF3333-CECD-4865-B2BA-A97063A9718E}']"
          s:ds="local:/Data/Tagline"
          s:id="{9C6D53E3-FE57-4638-AF7B-6D68304C7A94}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BE17F8C74-7318-428D-81D3-165F25583F9C%7D&amp;Styles=%7B54351712-760E-4F9D-8FC5-DAA43B0D8335%7D%7C%7BC048B4C8-561C-422B-8C91-F6C817904102%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=9"
          s:ph="/headless-main/sxa-page-content/background-page-content-0-1" />
        <r
          uid="{07924449-E37A-440B-B7D7-8F3C05F6398D}"
          p:after="*[1=2]"
          s:ds="{9B9AEBD2-16BE-4FC7-A465-21D5629CEFBB}"
          s:id="{F9905F68-21E8-4C6F-8B89-56BB99020D31}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=10"
          s:ph="headless-main" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Products
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "247be607-394a-4bf2-8c8a-509b07025dd9"
      Hint: Title
      Value: Products
    - ID: "3d30539f-d403-496a-a512-ac885b1a2f8b"
      Hint: Content
      Value: <p>The products you know, a brand you trust.</p>
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{171CCFD4-8543-428E-9A9B-8E6557E63B6D}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Products
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "81b9a170-7ef4-4e07-be51-095fe1177768"
- Language: "fr-CA"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Personnel
  Versions:
  - Version: 1
    Fields:
    - ID: "247be607-394a-4bf2-8c8a-509b07025dd9"
      Hint: Title
      Value: Personnel
    - ID: "3d30539f-d403-496a-a512-ac885b1a2f8b"
      Hint: Content
      Value: <p>Il n’existe qu’un seul avenir parfait. Le vôtre.</p>
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Personnel
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "128cb6ba-18ce-4fba-a29f-45cd8d2e4b80"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 個人のお客さま
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "247be607-394a-4bf2-8c8a-509b07025dd9"
      Hint: Title
      Value: 個人のお客さま
    - ID: "3d30539f-d403-496a-a512-ac885b1a2f8b"
      Hint: Content
      Value: <p>完璧な未来は一つしかない。 君のものだ</p>
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{171CCFD4-8543-428E-9A9B-8E6557E63B6D}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: 個人のお客さま
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9eea03e7-dfaa-41e5-916d-be486d4e0362"
