---
ID: "60eced56-64a4-4f35-8f1a-6481c01b8e10"
Parent: "8c4ce1c4-8ae4-4470-9ba3-10a2167ca6e4"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Verticals/BettyCrocker/Home page/Carousels/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6a8c25d5-421e-4eff-8ca9-f992444b2a5b"
