---
ID: "2d841051-479a-478c-b1b0-d3811279c541"
Parent: "e6856581-a59f-4eb6-97d9-3c78826f24fc"
Template: "e6856581-a59f-4eb6-97d9-3c78826f24fc"
Path: /sitecore/templates/Project/Verticals/Pages/Recipe/__Standard Values
SharedFields:
- ID: "5e387695-9a7c-4e82-a89c-8384928af97c"
  Hint: Thumbnail
  Value: |
    <image mediaid="{32909CAB-5F82-4428-A428-DF531E7776DD}" alt="Market report" height="" width="" hspace="" vspace="" />
- ID: "b9b271f5-3544-4a74-91b3-daf66aa53351"
  Hint: BackgroundImage
  Value: |
    <image mediaid="{10CB9C1E-EDEB-45AE-9598-EAD7CF3B3204}" alt="Blurred background image - fountain pen on notebook" height="" width="" hspace="" vspace="" />
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{63CC4D0D-63F1-4BFB-BF63-7EC9D231AFA8}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}">
        <r
          ds="{A9961429-A570-4E21-9A53-D1C8BF16CAC4}"
          id="{9D7DE58D-9DA4-43D8-8371-3C728A582ADC}"
          par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
          ph="/headless-main/sxa-article-content/article-meta-0-1"
          uid="{1333C7A2-2A6C-4310-AE74-8D5DE936F8B3}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "14ed42a8-e7fd-4164-9f77-d1f041ec8693"
      Hint: Title
      Value: $name
    - ID: "360e41db-ddb0-41ed-bdab-b033c5e261d1"
      Hint: Excerpt
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper neque id elit convallis, at varius lorem aliquet. Phasellus consequat, ante sed tristique commodo, felis mi vehicula justo, id finibus neque velit vitae nunc.
    - ID: "7a3d5840-19ca-4e0b-86ad-5b84551fba64"
      Hint: Ingredients
      Value: |
        <p><strong>Lorem Ipsum Finance</strong></p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper neque id elit convallis, at varius lorem aliquet. Phasellus consequat, ante sed tristique commodo, felis mi vehicula justo, id finibus neque velit vitae nunc.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin at mauris vel purus vestibulum consectetur. Nam efficitur lectus auctor, hendrerit ligula nec, pharetra ex.</p>
        <p>Suspendisse potenti. Sed ac arcu scelerisque, hendrerit risus eu, ultricies libero. Pellentesque ut magna eu elit fringilla viverra. Quisque ullamcorper orci a magna finibus, nec feugiat urna semper. Praesent blandit purus vel ligula finibus, nec fermentum dui ultrices. Nulla vitae justo a felis luctus dignissim. Aliquam eu tortor eget libero placerat semper.</p>
        <p>In consequat, libero sed viverra placerat, metus lectus accumsan velit, a suscipit elit dui sit amet justo. Fusce vitae purus vel justo aliquam hendrerit. Integer pretium mi vel ex convallis, vel dignissim ex finibus.</p>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "abd474e2-142d-4235-8f33-ec60c6b3597f"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "14ed42a8-e7fd-4164-9f77-d1f041ec8693"
      Hint: Title
      Value: $name
    - ID: "360e41db-ddb0-41ed-bdab-b033c5e261d1"
      Hint: Excerpt
      Value: Découvrez les clés de la littératie financière grâce aux conseils d'experts en budgétisation, épargne, investissement et planification de la retraite. Découvrez des astuces et des stratégies pratiques pour prendre le contrôle de vos finances et bâtir un avenir sûr pour vous et votre famille.
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: $name
    - ID: "7a3d5840-19ca-4e0b-86ad-5b84551fba64"
      Hint: Ingredients
      Value: |
        <p><strong>Lorem Ipsum Finance</strong></p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper neque id elit convallis, at varius lorem aliquet. Phasellus consequat, ante sed tristique commodo, felis mi vehicula justo, id finibus neque velit vitae nunc.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin at mauris vel purus vestibulum consectetur. Nam efficitur lectus auctor, hendrerit ligula nec, pharetra ex.</p>
        <p>Suspendisse potenti. Sed ac arcu scelerisque, hendrerit risus eu, ultricies libero. Pellentesque ut magna eu elit fringilla viverra. Quisque ullamcorper orci a magna finibus, nec feugiat urna semper. Praesent blandit purus vel ligula finibus, nec fermentum dui ultrices. Nulla vitae justo a felis luctus dignissim. Aliquam eu tortor eget libero placerat semper.</p>
        <p>In consequat, libero sed viverra placerat, metus lectus accumsan velit, a suscipit elit dui sit amet justo. Fusce vitae purus vel justo aliquam hendrerit. Integer pretium mi vel ex convallis, vel dignissim ex finibus.</p>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ef884ca0-4caf-478c-922a-789857aef268"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "14ed42a8-e7fd-4164-9f77-d1f041ec8693"
      Hint: Title
      Value: $name
    - ID: "360e41db-ddb0-41ed-bdab-b033c5e261d1"
      Hint: Excerpt
      Value: "Maintaining a healthy work-life balance is crucial for employee satisfaction and productivity. Explore practical strategies that employees can implement to support their team’s well-being and create a more balanced, productive work environment."
    - ID: "7a3d5840-19ca-4e0b-86ad-5b84551fba64"
      Hint: Ingredients
      Value: |
        <p><strong>Lorem Ipsum Finance</strong></p>
        <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ullamcorper neque id elit convallis, at varius lorem aliquet. Phasellus consequat, ante sed tristique commodo, felis mi vehicula justo, id finibus neque velit vitae nunc.</p>
        <p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin at mauris vel purus vestibulum consectetur. Nam efficitur lectus auctor, hendrerit ligula nec, pharetra ex.</p>
        <p>Suspendisse potenti. Sed ac arcu scelerisque, hendrerit risus eu, ultricies libero. Pellentesque ut magna eu elit fringilla viverra. Quisque ullamcorper orci a magna finibus, nec feugiat urna semper. Praesent blandit purus vel ligula finibus, nec fermentum dui ultrices. Nulla vitae justo a felis luctus dignissim. Aliquam eu tortor eget libero placerat semper.</p>
        <p>In consequat, libero sed viverra placerat, metus lectus accumsan velit, a suscipit elit dui sit amet justo. Fusce vitae purus vel justo aliquam hendrerit. Integer pretium mi vel ex convallis, vel dignissim ex finibus.</p>
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b2101f42-b52c-4c66-a5b9-4f05f135bbfe"
